import { NextResponse } from "next/server";
import { z } from "zod";
import { createAdminSupabase } from "@/lib/supabase/admin";
import { resolvePortalClient } from "@/lib/portals/token";
import {
  enforceBlocklist,
  enforceDomainBlocklist,
  normalizeDomain,
} from "@/lib/portals/enforce-blocklist";

// POST /api/portal/[token]/dnc/csv — bulk-import parsed DNC rows.
//
// Rewritten 2026-06 to match the Agents CSV pattern: ONE batched
// upsert (idempotent on (client_id, dedup_key) thanks to migration
// 0042), provider blocklist pushes fan out in parallel chunks in
// the background. Previously the route did one INSERT + one
// per-row provider call + a 250 ms throttle, so a 300-row CSV took
// ≥75 s and the page sat frozen.
//
// dedup_key is a STORED GENERATED column on client_dnc_entries —
// lower(email) for agent rows, lower(domain) for company rows. The
// insert never sets it directly; Postgres computes it and the
// unique index enforces "one row per (client_id, normalized key)".

export const dynamic = "force-dynamic";
export const maxDuration = 300;

const rowSchema = z.object({
  kind: z.enum(["agent", "company"]),
  name: z.string().trim().min(1).max(160),
  email: z.string().trim().email().nullable().optional(),
  phone: z.string().trim().max(40).nullable().optional(),
  brokerage: z.string().trim().max(160).nullable().optional(),
  domain: z.string().trim().max(255).nullable().optional(),
  notes: z.string().trim().max(2000).nullable().optional(),
});

const schema = z.object({
  rows: z.array(rowSchema).min(1).max(5000),
});

// Parallelism for the post-response provider sync — same shape the
// Agents route uses.
const PUSH_CONCURRENCY = 10;

export async function POST(
  request: Request,
  context: { params: Promise<{ token: string }> },
) {
  const { token } = await context.params;
  const client = await resolvePortalClient(token);
  if (!client) {
    return NextResponse.json({ error: "Portal not found" }, { status: 404 });
  }

  const parsed = schema.safeParse(await request.json().catch(() => null));
  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues[0]?.message ?? "Invalid input" },
      { status: 400 },
    );
  }

  const admin = createAdminSupabase();

  // Normalise + dedup within the batch BEFORE the DB sees the rows.
  // Agent rows by lowercase email; company rows by normalised domain.
  // Rows with neither (a stray name-only entry) just pass through —
  // the unique index's NULL distinct semantics let multiples through.
  const seenEmail = new Set<string>();
  const seenDomain = new Set<string>();
  const rows = parsed.data.rows
    .map((r) => ({
      ...r,
      email: r.email ? r.email.toLowerCase() : null,
      domain: r.kind === "company" ? normalizeDomain(r.domain ?? "") : null,
    }))
    .filter((r) => {
      if (r.kind === "company") {
        if (!r.domain) return true;
        if (seenDomain.has(r.domain)) return false;
        seenDomain.add(r.domain);
        return true;
      }
      if (!r.email) return true;
      if (seenEmail.has(r.email)) return false;
      seenEmail.add(r.email);
      return true;
    });

  // Single batched upsert. dedup_key is generated by Postgres from
  // (kind, email, domain) — see migration 0042 — so we don't supply
  // it here. ignoreDuplicates makes re-uploading the same file a
  // no-op for already-imported rows.
  const insertRows = rows.map((r) => ({
    client_id: client.id,
    kind: r.kind,
    name: r.name,
    email: r.email,
    phone: r.phone ?? null,
    brokerage: r.kind === "company" ? null : (r.brokerage ?? null),
    domain: r.domain,
    notes: r.notes ?? null,
    added_by: "client",
    pushed_to_instantly: false,
    pushed_to_emailbison: false,
    push_error: null as string | null,
  }));

  const { data: inserted, error } = await admin
    .from("client_dnc_entries")
    .upsert(insertRows, {
      onConflict: "client_id,dedup_key",
      ignoreDuplicates: true,
    })
    .select("id, kind, email, domain");
  if (error) {
    return NextResponse.json({ error: error.message }, { status: 400 });
  }

  // Async provider push. We respond immediately with the row count;
  // pushed_to_instantly / pushed_to_emailbison flip per row as each
  // call completes, surfacing on the next portal refresh. Same
  // pattern as the Agents route.
  const pushPromise = (async () => {
    const targets = (inserted ?? []) as Array<{
      id: string;
      kind: "agent" | "company";
      email: string | null;
      domain: string | null;
    }>;
    const pushable = targets.filter(
      (t) => (t.kind === "company" && t.domain) || (t.kind === "agent" && t.email),
    );
    for (let i = 0; i < pushable.length; i += PUSH_CONCURRENCY) {
      const chunk = pushable.slice(i, i + PUSH_CONCURRENCY);
      await Promise.allSettled(
        chunk.map(async (t) => {
          const result =
            t.kind === "company"
              ? await enforceDomainBlocklist(t.domain!)
              : await enforceBlocklist(t.email!);
          await admin
            .from("client_dnc_entries")
            .update({
              pushed_to_instantly: result.pushedInstantly,
              pushed_to_emailbison: result.pushedEmailBison,
              push_error: result.error,
            })
            .eq("id", t.id);
        }),
      );
    }
  })();
  void pushPromise;

  return NextResponse.json({
    ok: true,
    inserted: inserted?.length ?? 0,
    // Provider push completes asynchronously; the UI reads pushed_to_*
    // on the next refresh.
    pushScheduled: (inserted ?? []).length,
  });
}
